In [16]:
import sys
sys.executable

'd:\\Machine Learning\\Data-Gathering\\my_env\\Scripts\\python.exe'

In [17]:
import pandas as pd
import numpy as np
import requests

In [18]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [19]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [20]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,40.6274,8.718,30125
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.5648,8.687,22764
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,22.1675,8.572,13792
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,24.9226,8.600,17320
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,17.2619,8.600,9895

In [21]:
df=pd.DataFrame()

In [23]:
df

Empty DataFrame
Columns: []
Index: []

In [25]:
dfs = []
for i in range(1, 429):
    response = requests.get(
        f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}'
    )
    
    temp_df = pd.DataFrame(response.json()['results'])[
        ['id','title','overview','release_date','popularity','vote_average','vote_count']
    ]
    
    dfs.append(temp_df)

df = pd.concat(dfs, ignore_index=True)

In [26]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,40.6274,8.718,30125
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.5648,8.687,22764
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,22.1675,8.572,13792
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,24.9226,8.600,17320
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,17.2619,8.600,9895
...,...,...,...,...,...,...,...
8555,9021,The Santa Clause 2,Better watch out! The big guy in red is coming...,2002-09-29,2.0783,6.000,1414
8556,531503,Point Blank,A nurse is forced to spring a wounded murder s...,2019-07-12,1.9045,5.999,571
8557,442249,The First Purge,To push the crime rate below one percent for t...,2018-07-04,3.6737,5.999,4201
8558,340487,Certain Women,Three strong-willed women strive to forge thei...,2016-09-25,2.0720,5.999,379
8559,11678,Vertical Limit,"Trapped near the summit of K2, the world's sec...",2000-12-08,3.4635,5.999,1124